
import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Archana Kumari
 */
public class SIGNUP extends javax.swing.JFrame {
    String sex;
    ImageIcon i=new ImageIcon("src/28.png");
    /**
     * Creates new form SIGNUP
     */
    public SIGNUP() {
        initComponents();
        b1.setEnabled(false);
         this.setResizable(false);
         p1.setEnabled(false);
          p2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        p1 = new javax.swing.JPasswordField();
        p2 = new javax.swing.JPasswordField();
        t31 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGN UP");
        setBounds(new java.awt.Rectangle(400, 125, 0, 0));
        setIconImage(i.getImage());
        setResizable(false);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        p1.setBackground(new java.awt.Color(0, 51, 102));
        p1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 255, 255));
        p1.setToolTipText("Enter Password With 6-26 Characters Containing At Least One Uppercase Letter & Number");
        p1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 255, 255)));
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        jPanel1.add(p1);
        p1.setBounds(620, 300, 420, 50);

        p2.setBackground(new java.awt.Color(0, 51, 102));
        p2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 255, 255));
        p2.setToolTipText("Enter Password With 6-26 Characters Containing At Least One Uppercase Letter & Number");
        p2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 255, 255)));
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        jPanel1.add(p2);
        p2.setBounds(620, 400, 420, 50);

        t31.setEditable(false);
        t31.setBackground(new java.awt.Color(0, 51, 102));
        t31.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        t31.setForeground(new java.awt.Color(255, 255, 255));
        t31.setText("RE-TYPE PASSWORD");
        t31.setBorder(null);
        t31.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t31.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                t31MouseMoved(evt);
            }
        });
        t31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t31MouseClicked(evt);
            }
        });
        t31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t31ActionPerformed(evt);
            }
        });
        jPanel1.add(t31);
        t31.setBounds(620, 360, 390, 50);

        t1.setEditable(false);
        t1.setBackground(new java.awt.Color(0, 51, 102));
        t1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setToolTipText("FILL NAME AND GENDER TO GET UNIQUE ID");
        t1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 255, 255)));
        t1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                t1MouseMoved(evt);
            }
        });
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(720, 70, 330, 50);

        t5.setEditable(false);
        t5.setBackground(new java.awt.Color(0, 51, 102));
        t5.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        t5.setForeground(new java.awt.Color(255, 255, 255));
        t5.setText("GENDER");
        t5.setBorder(null);
        t5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                t5MouseMoved(evt);
            }
        });
        t5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t5MouseClicked(evt);
            }
        });
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        jPanel1.add(t5);
        t5.setBounds(620, 200, 100, 50);

        t7.setEditable(false);
        t7.setBackground(new java.awt.Color(0, 51, 102));
        t7.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        t7.setForeground(new java.awt.Color(255, 255, 255));
        t7.setText("CREATE PASSWORD");
        t7.setBorder(null);
        t7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                t7MouseMoved(evt);
            }
        });
        t7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t7MouseClicked(evt);
            }
        });
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        jPanel1.add(t7);
        t7.setBounds(620, 260, 220, 50);

        t2.setBackground(new java.awt.Color(0, 51, 102));
        t2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setText("Enter Name Here");
        t2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 255, 255)));
        t2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                t2MouseMoved(evt);
            }
        });
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
        });
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2);
        t2.setBounds(720, 130, 330, 50);

        t8.setEditable(false);
        t8.setBackground(new java.awt.Color(0, 51, 102));
        t8.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        t8.setForeground(new java.awt.Color(255, 255, 255));
        t8.setText("NAME");
        t8.setBorder(null);
        t8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                t8MouseMoved(evt);
            }
        });
        t8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t8MouseClicked(evt);
            }
        });
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        jPanel1.add(t8);
        t8.setBounds(620, 130, 390, 50);

        t9.setEditable(false);
        t9.setBackground(new java.awt.Color(0, 51, 102));
        t9.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        t9.setForeground(new java.awt.Color(255, 255, 255));
        t9.setText("USER ID");
        t9.setBorder(null);
        t9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                t9MouseMoved(evt);
            }
        });
        t9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t9MouseClicked(evt);
            }
        });
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        jPanel1.add(t9);
        t9.setBounds(620, 70, 100, 50);

        r2.setBackground(new java.awt.Color(0, 102, 255));
        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        r2.setForeground(new java.awt.Color(153, 204, 255));
        r2.setText("FEMALE");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        jPanel1.add(r2);
        r2.setBounds(890, 210, 140, 40);

        r1.setBackground(new java.awt.Color(51, 102, 255));
        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        r1.setForeground(new java.awt.Color(153, 204, 255));
        r1.setText("MALE");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jPanel1.add(r1);
        r1.setBounds(730, 210, 130, 40);

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("GET ID");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jButton1PropertyChange(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(620, 470, 170, 70);

        b1.setBackground(new java.awt.Color(0, 51, 102));
        b1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("SIGN UP");
        b1.setBorder(null);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        b1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                b1PropertyChange(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(860, 470, 170, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/24.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 62, 57);

        jLabel4.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("HOTEL PARADISE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 70, 470, 60);

        jLabel3.setFont(new java.awt.Font("Pristina", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 153));
        jLabel3.setText("# Serving over 30 Years.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 260, 520, 40);

        jLabel5.setFont(new java.awt.Font("Pristina", 1, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 153));
        jLabel5.setText("# Experince the best of Goa with Paradise");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 170, 520, 40);

        jLabel6.setFont(new java.awt.Font("Pristina", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 153));
        jLabel6.setText("# Spread over 50 Countries.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 300, 520, 40);

        jLabel7.setFont(new java.awt.Font("Pristina", 1, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 153));
        jLabel7.setText("    Group Of Hotels.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 220, 520, 40);

        jLabel8.setFont(new java.awt.Font("Mistral", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("JOIN US TODAY !!");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(670, 10, 340, 50);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 51, 102));
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(204, 255, 255)));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(600, -10, 470, 580);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/10.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-10, -10, 860, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void t31MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t31MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_t31MouseMoved

    private void t31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t31MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t31MouseClicked

    private void t31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t31ActionPerformed

    private void t1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_t1MouseMoved

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t1MouseClicked

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_t5MouseMoved

    private void t5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t5MouseClicked

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_t7MouseMoved

    private void t7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t7MouseClicked

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void t8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_t8MouseMoved

    private void t8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t8MouseClicked

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_t2MouseMoved

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
        // TODO add your handling code here:
        t2.setText("");
    }//GEN-LAST:event_t2MouseClicked

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
         t2.setText("");
    }//GEN-LAST:event_t2ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jPanel1MouseClicked

    private void t9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_t9MouseMoved

    private void t9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_t9MouseClicked

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String n,na,no,a,b,d,f="";
        int ui=0,u=0;
        char c,h,s;
        n=t2.getText();
        na=n.toUpperCase();
        c=na.charAt(0);
        int i=0;
        while(na.charAt(i)!=' ')
            i++;
        h=na.charAt(i+1);
        s=sex.charAt(0);
        ui=u+1;
        u=ui;
        no=ui+"";
        a=c+"";
        b=h+"";
        d=s+"";
        String id=a+b+d+no;
        try
        {
          Class.forName("com.mysql.cj.jdbc.Driver");
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/HOTEL","root","2327");
          Statement st = con.createStatement();
          ResultSet rs = st.executeQuery("Select * from Login;");
            int g=0;
                while(rs.next())
                {
                    String userid=rs.getString(1);
                    if (id.equals(userid))
                    {
                        ui=u+1;
                        no=ui+"";
                        id=a+b+d+no;
                    }
                }
        }
         catch(Exception e)
         {
             System.out.println(e);
         }
        if(!(t2.getText().equalsIgnoreCase(f)) && (r1.isSelected() || r2.isSelected()))
        {
        t1.setText(id);
        jButton1.setEnabled(false);
        b1.setEnabled(true);
        p1.setEnabled(true);
        p2.setEnabled(true);
        }
        else
        JOptionPane.showMessageDialog(null,"Please enter your details to get your USER ID");
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jButton1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1PropertyChange

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        String id=t1.getText();
        String na=t2.getText();
        String pw=String.valueOf(p1.getPassword());
        String pw1=String.valueOf(p2.getPassword());
        int p=pw.length();
        int pa=pw1.length();
        int i=0,c=0,n=0,m=0;
        if(p==pa && p>=6)
        { 
         for(;i<p;i++)
         {
             char ch=pw.charAt(i);
             if(ch>='A' && ch<='Z')
             c++;
             if(ch>='0' && ch<='9')
             n++;    
         } 
            if(n>0 && c>0)
            {
                 try
            {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/HOTEL","root","2327");
            Statement st=con.createStatement();
            int z=st.executeUpdate("Insert into Login VALUES('"+id+"','"+na+"','"+sex+"','"+pw+"');");
            JOptionPane.showMessageDialog(null,"CONGRATS!! YOUR ACCOUNT HAS BEEN CREATED.");
            con.close();
            st.close();
            }
        catch(Exception e)
            {
            System.out.println(e);
            }
            this.dispose();
            LOGIN o=new LOGIN();
            o.setVisible(true);
            }
            else
            {
                p1.setText("");
                p2.setText("");
                JOptionPane.showMessageDialog(null,"YOUR PASSWORD SHOULD AT LEAST HAVE 1 UPPERCASE LETTER AND 1 NUMBER");
            }}
        else
        JOptionPane.showMessageDialog(null,("PASSWORD MUST BE OF 6 OR MORE CHARACTERS."));
        
    }//GEN-LAST:event_b1ActionPerformed

    private void b1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_b1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_b1PropertyChange

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        LOGIN l= new LOGIN();
        l.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
        sex="MALE";
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
        sex="FEMALE";
    }//GEN-LAST:event_r2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGNUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t31;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
